site_name: dotnet
docs_dir: ./docs

nav:
  - WireMock.NET: index.md
  - What is WireMock.Net: what-is-wiremock-net.md
  - WireMock Java Compatibility: wiremock-java-compatibility.md
  - References: references.md
  - Settings: settings.md
  - Admin REST API:
    - Admin API Reference: admin-api-reference.md
    - Mapping: mapping.md
  - Proxying: proxying.md
  - Stubbing: stubbing.md
  - Webhook: webhook.md
  - WireMock commandline parameters: wiremock-commandline-parameters.md
  - Request Matching:
    - Request Matching: request-matching.md
    - Request Matchers: request-matchers.md
    - Request Matching Tips: request-matching-tips.md
    - Request Matcher FormUrlEncodedMatcher: request-matcher-formurlencodedmatcher.md
    - Request Matching CSharpCode: request-matching-csharpcode.md
    - Request Matching GraphQLMatcher: request-matching-graphqlmatcher.md
    - Request Matching JsonMatcher: request-matching-jsonmatcher.md
    - Request Matching JsonPartialMatcher: request-matching-jsonpartialmatcher.md
    - Request Matching JsonPartialWildcardMatcher: request-matching-jsonpartialwildcardmatcher.md
    - Request Matching JsonPathMatcher: request-matching-jsonpathmatcher.md
    - Request Matching MimePartMatcher: request-matching-mimepartmatcher.md
    - Request Matching ProtoBuf: request-matching-protobuf.md

  - Response Templating: response-templating.md
  - Unit Testing:
    - Using WireMock in UnitTests: using-wiremock-in-unittests.md
    - Using WireMock.Net.Testcontainers: using-wiremock-net-testcontainers.md
    - Using WireMock.Net.Aspire: using-wiremock-net-aspire.md
    - FluentAssertions: fluentassertions.md
  - Using WireMock:
    - WireMock as dotnet tool: wiremock-as-dotnet-tool.md
    - WireMock as a standalone process: wiremock-as-a-standalone-process.md
    - WireMock as a (Azure) Web App: wiremock-as-a-azure-web-app.md
    - WireMock as a Windows Service: wiremock-as-a-windows-service.md
  - Advanced:
    - Scenarios and States: scenarios-and-states.md
    - Pact: pact.md
    - Faults: faults.md
    - Using HTTPS (SSL): using-https-ssl.md
    - Cors: cors.md
    - KestrelServerOptions: kestrelserveroptions.md
    - RegexExtended: regexextended.md
    - MyGet preview versions: myget-preview-versions.md
    - Development Information: development-information.md
  - Errors:
    - Xamarin---Could-not-load-file-or-assembly: xamarin-could-not-load-file-or-assembly.md
    - Conflict-on-Microsoft.CodeAnalysis.CSharp: conflict-on-microsoft-codeanalysis-csharp.md
    - Could not load file or assembly RestEase: could-not-load-file-or-assembly-restease.md
    - MimeKit and MimeKitLite: mimekit-and-mimekitlite.md