---
name: "Updatecli"

on:
  workflow_dispatch:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   # trigger every hour the following pipeline
  #   - cron: '0 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    # Ensure we only run the following pipeline from main branch
    # with a GITHUB_TOKEN that has "contents: write" permission
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Updatecli Binary
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli in enforce mode
        run: "updatecli apply --config .github/updatecli/updatecli.d"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
